javascript:(function(){
    const wordsToMatch = [
        "automations",
        "clickup objects",
        "clickup",
        "clickapps",
        "clickapp",
        "automations menu",
        "custom automation",
        "automations shortcuts",
        "bulk action toolbar",
        "multitask toolbar",
        "email clickapp",
        "time estimate clickapp",
        "milestone clickapp",
        "not started status group",
        "priority clickapp",
        "relationships clickapp",
        "sprints clickapp",
        "tags clickapp",
        "command center",
        "community templates",
        "label custom field",
        "date custom field",
        "dropdown custom field",
        "formula fields",
        "formula field",
        "phone custom field",
        "website custom field",
        "custom field",
        "drag and drop",
        "form view",
        "clean layout",
        "modern layout",
        "simple layout",
        "lineup",
        "dark mode",
        "everyone mode",
        "high contrast mode",
        "light mode",
        "me mode",
        "offline mode",
        "page settings menu",
        "page template",
        "partner program",
        "affiliate program",
        "referral program",
        "personal view",
        "priority",
        "priorities",
        "free forever plan",
        "unlimited plan",
        "business plan",
        "business plus plan",
        "enterprise plan",
        "quickswitch",
        "quick action menu",
        "quick create task button",
        "reminder feature",
        "rich text format",
        "map view sidebar",
        "people sidebar",
        "single sign on",
        "saml",
        "sso",
        "third party identity provider",
        "smart alignment guidelines",
        "sprint feature",
        "sprint folder",
        "not started",
        "custom task ids",
        "task id",
        "task view",
        "list view",
        "board view",
        "calendar view",
        "view templates",
        "template center",
        "trash icon",
        "two factor authentication",
        "two way sync",
        "activity view",
        "box view",
        "chat view",
        "doc view",
        "embed view",
        "gantt view",
        "map view",
        "mind maps",
        "task mode",
        "blank mode",
        "table view",
        "timeline view",
        "workload view",
        "views bar",
        "website card",
        "whiteboard",
        "assignee widget",
        "bar chart widget",
        "custom widget",
        "pie chart",
        "portfolio",
        "dashboard widget",
        "embed widget",
        "task list widget",
        "workspace",
        "done status",
        "home list",
        "listed",
        "listing",
        'active status',
        'closed status',
        'done status',
        'documentation',
        'automation', 
        'action', 
        'conditions',
        'trigger',
        'clip',
        'column',
        'dashboard',
        'doc',
        'favorites',
        'folder',
        'formula',
        'goal',
        'hierarchy',
        'home',
        'list',
        'notepad',
        'profiles',
        'proofing',
        'pulse',
        'sidebar',
        'space',
        'table',
        'targets',
        'teams',
        'trash',
        'v2',
        'sprint'
      ];
      const replacementWords = [
        "Automations",
        "ClickUp Objects",
        "ClickUp",
        "ClickApps",
        "ClickApp",
        "Automations menu",
        "Custom Automation",
        "Automations Shortcuts",
        "Bulk Action Toolbar",
        "Multitask Toolbar",
        "Email ClickApp",
        "Time Estimate ClickApp",
        "Milestone ClickApp",
        "Not Started Status Group",
        "Priority ClickApp",
        "Relationships ClickApp",
        "Sprints ClickApp",
        "Tags ClickApp",
        "Command Center",
        "Community templates",
        "Label Custom Field",
        "Date Custom Field",
        "Dropdown Custom Field",
        "Formula Fields",
        "Formula Field",
        "Phone Custom Field",
        "Website Custom Field",
        "Custom Field",
        "drag-and-drop",
        "Form view",
        "Clean layout",
        "Modern layout",
        "Simple layout",
        "LineUp",
        "Dark Mode",
        "Everyone Mode",
        "High Contrast Mode",
        "Light Mode",
        "Me Mode",
        "Offline Mode",
        "Page settings menu",
        "Page template",
        "Partner Program",
        "Affiliate Program",
        "Referral Program",
        "Personal view",
        "Priority",
        "Priorities",
        "Free Forever Plan",
        "Unlimited Plan",
        "Business Plan",
        "Business Plus Plan",
        "Enterprise Plan",
        "QuickSwitch",
        "Quick Action menu",
        "Quick Create task button",
        "Reminder feature",
        "Rich Text Format",
        "Map View Sidebar",
        "People Sidebar",
        "single sign-on",
        "SAML",
        "SSO",
        "third-party identity provider",
        "Smart Alignment Guidelines",
        "Sprint feature",
        "Sprint Folder",
        "Not Started",
        "Custom Task IDs",
        "task ID",
        "Task view",
        "List view",
        "Board view",
        "Calendar view",
        "View templates",
        "Template Center",
        "trash icon",
        "two-factor authentication",
        "two-way sync",
        "Activity view",
        "Box view",
        "Chat view",
        "Doc view",
        "Embed view",
        "Gantt view",
        "Map view",
        "Mind Maps",
        "Task Mode",
        "Blank Mode",
        "Table view",
        "Timeline view",
        "Workload view",
        "Views Bar",
        "Website Card",
        "Whiteboard",
        "Assignee widget",
        "Bar Chart widget",
        "Custom widget",
        "Pie Chart",
        "Portfolio",
        "Dashboard widget",
        "Embed widget",
        "Task List widget",
        "Workspace",
        "Done status",
        "home list",
        "listed",
        "listing",
        'Active status',
        'Closed status',
        'Done status',
        'documentation',
        'Automation', 
        'Action', 
        'Conditions',
        'Trigger',
        'Clip',
        'Column',
        'Dashboard',
        'Doc',
        'Favorites',
        'Folder',
        'Formula',
        'Goal',
        'Hierarchy',
        'Home',
        'List',
        'Notepad',
        'Profiles',
        'Proofing',
        'Pulse',
        'Sidebar',
        'Space',
        'Table',
        'Targets',
        'Teams',
        'Trash',
        'V2',
        'Sprint'
      ];
var textInput = document.querySelector("#\\:rh\\:--primary-pane > div.sc-435c7v-2.jgaJWs.StyledPaneContent-sc-1b38mbh-0.lasZfd > div > div > div > div.zendesk-editor--rich-text-container.sc-1j8a31a-0.bszatj");
var pList = textInput.querySelectorAll("p"); 
    for (var i = 0; i < pList.length; i++) {
        var pTag = pList[i];
        var originalText = pTag.innerHTML;
        var replacedText = "";
            for (var j = 0; j < wordsToMatch.length; j++) {
                var wordToMatch = wordsToMatch[j];
                var replacementWord = replacementWords[j];
                var regex = new RegExp('\\b' + wordToMatch + '\\b', 'g');
                if (j == 0) {
                    replacedText = originalText.replace(regex, replacementWord);
                } else {
                    replacedText = replacedText.replace(regex, replacementWord);
                }
                console.log("words to match length: " + wordsToMatch.length.toString());
                console.log("current index: " + j.toString());
                console.log("replacing: " + replacedText);
            }
        console.log("final replaced text: " + replacedText);
        const fragment = document.createDocumentFragment();
        const p = pTag;
        p.contentEditable = true;
        p.textContent = replacedText;
        fragment.appendChild(p);
        textInput.appendChild(fragment);            
    }
})();



